### ISSUE TITLE
无法使用？？

### ISSUE THREAD

**Issue by rollingstonemark** [eqblog/91_porn_spider#14]
`Traceback (most recent call last):
  File "91_spider.py", line 25, in <module>
    get_page=requests.get(url=page_url)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
`

**Comment by rollingstonemark** [comment]
提示这个错误是什么原因？

**Comment by Pan-yongyong** [comment]
要翻墙兄弟

**Comment by IlIlIlllIIl** [comment]
把你的代理写进request里
