### ISSUE TITLE
91_js.py 调用js2py的错误

### ISSUE THREAD

**Issue by zzxyangzhou** [eqblog/91_porn_spider#20]
Traceback (most recent call last):
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\js2py\evaljs.py", line 193, in execute
    compiled = cache[hashkey]
KeyError: b'pF\x1d\xa8\xb9Ll\xa5\xd2\xfd\xa3&\x0cZ\x8c;'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "91_js.py", line 23, in <module>
    js.execute(jsdata)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\js2py\evaljs.py", line 196, in execute
    js, '', use_compilation_plan=use_compilation_plan)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\js2py\translators\translator.py", line 65, in translate_js
    parsed = parser.parse(js)  # js to esprima syntax tree
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 3008, in parse
    program = self.parseProgram()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 2974, in parseProgram
    body = self.parseScriptBody()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 2963, in parseScriptBody
    statement = self.parseStatementListItem()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 2110, in parseStatementListItem
    return self.parseStatement()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 2705, in parseStatement
    expr = self.parseExpression()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 2076, in parseExpression
    expr = self.isolateCoverGrammar(self.parseAssignmentExpression)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1161, in isolateCoverGrammar
    result = parser()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 2038, in parseAssignmentExpression
    expr = self.parseConditionalExpression()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1931, in parseConditionalExpression
    expr = self.inheritCoverGrammar(self.parseBinaryExpression)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1176, in inheritCoverGrammar
    result = parser()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1876, in parseBinaryExpression
    left = self.inheritCoverGrammar(self.parseUnaryExpression)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1176, in inheritCoverGrammar
    result = parser()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1852, in parseUnaryExpression
    expr = self.parsePostfixExpression()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1794, in parsePostfixExpression
    self.parseLeftHandSideExpressionAllowCall)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1176, in inheritCoverGrammar
    result = parser()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1717, in parseLeftHandSideExpressionAllowCall
    self.parseNewExpression if self.matchKeyword('new') else self.
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1176, in inheritCoverGrammar
    result = parser()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1652, in parsePrimaryExpression
    self.throwUnexpectedToken(self.lex())
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1046, in throwUnexpectedToken
    raise self.unexpectedTokenError(token, message)
js2py.internals.simplex.JsException: SyntaxError: Line 1: Unexpected token <
PS F:\xampp\htdocs\91\python> python 91_js.py
Traceback (most recent call last):
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\js2py\evaljs.py", line 193, in execute
    compiled = cache[hashkey]
KeyError: b'pF\x1d\xa8\xb9Ll\xa5\xd2\xfd\xa3&\x0cZ\x8c;'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "91_js.py", line 23, in <module>
    js.execute(jsdata)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\js2py\evaljs.py", line 196, in execute
    js, '', use_compilation_plan=use_compilation_plan)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\js2py\translators\translator.py", line 65, in translate_js
    parsed = parser.parse(js)  # js to esprima syntax tree
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 3008, in parse
    program = self.parseProgram()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 2974, in parseProgram
    body = self.parseScriptBody()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 2963, in parseScriptBody
    statement = self.parseStatementListItem()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 2110, in parseStatementListItem
    return self.parseStatement()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 2705, in parseStatement
    expr = self.parseExpression()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 2076, in parseExpression
    expr = self.isolateCoverGrammar(self.parseAssignmentExpression)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1161, in isolateCoverGrammar
    result = parser()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 2038, in parseAssignmentExpression
    expr = self.parseConditionalExpression()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1931, in parseConditionalExpression
    expr = self.inheritCoverGrammar(self.parseBinaryExpression)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1176, in inheritCoverGrammar
    result = parser()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1876, in parseBinaryExpression
    left = self.inheritCoverGrammar(self.parseUnaryExpression)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1176, in inheritCoverGrammar
    result = parser()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1852, in parseUnaryExpression
    expr = self.parsePostfixExpression()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1794, in parsePostfixExpression
    self.parseLeftHandSideExpressionAllowCall)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1176, in inheritCoverGrammar
    result = parser()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1717, in parseLeftHandSideExpressionAllowCall
    self.parseNewExpression if self.matchKeyword('new') else self.
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1176, in inheritCoverGrammar
    result = parser()
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1652, in parsePrimaryExpression
    self.throwUnexpectedToken(self.lex())
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python37\lib\site-packages\pyjsparser\parser.py", line 1046, in throwUnexpectedToken
    raise self.unexpectedTokenError(token, message)
js2py.internals.simplex.JsException: SyntaxError: Line 1: Unexpected token <

**Comment by zzxyangzhou** [comment]
91好像增加了Cloudflare
