### ISSUE TITLE
python3.4 的报错，字符编码问题

### ISSUE THREAD

**Issue by zzjzz9266a** [eqblog/91_porn_spider#3]
Traceback (most recent call last):
  File "91_spider.py", line 42, in <module>
    if os.path.exists(str(t))==False:
  File "/usr/lib64/python3.4/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-10: ordinal not in range(128)

**Comment by tea1111980** [comment]
用最新版 Python 没事。

**Comment by Edwardmark** [comment]
@tea1111980 请问你的版本是?我用的3.6.8也有这个问题
